<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="compaq-PC" ignored="0" name="MergeLead" tests="2" failures="1" timestamp="28 Nov 2017 03:05:52 GMT" time="61.409" errors="0">
  <testcase name="creatLead" time="29.584" classname="learntestng.CreateLead"/>
  <testcase name="mergelead" time="61.317" classname="learntestng.MergeLead">
    <failure type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException
	at framework.SeMethods.locateElement(SeMethods.java:77)
	at learntestng.MergeLead.mergelead(MergeLead.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- mergelead -->
</testsuite> <!-- MergeLead -->
